# Generated by Django 6.0 on 2025-12-05 06:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('permanent_address', models.TextField(verbose_name='Permanent Address')),
                ('current_address', models.TextField(verbose_name='Current Address')),
                ('father_name', models.CharField(max_length=200, verbose_name="Father's Name")),
                ('mother_name', models.CharField(max_length=200, verbose_name="Mother's Name")),
                ('spouse_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Spouse Name')),
                ('citizenship_number', models.CharField(max_length=50, unique=True, verbose_name='Citizenship Number')),
                ('citizenship_issue_date', models.DateField(blank=True, null=True, verbose_name='Citizenship Issue Date')),
                ('citizenship_issue_district', models.CharField(blank=True, max_length=100, null=True, verbose_name='Citizenship Issue District')),
                ('membership_type', models.CharField(choices=[('REGULAR', 'Regular'), ('LIFETIME', 'Lifetime Membership')], default='REGULAR', max_length=20, verbose_name='Membership Type')),
                ('membership_number', models.CharField(max_length=50, unique=True, verbose_name='Membership Number')),
                ('join_date', models.DateField(default=django.utils.timezone.now, verbose_name='Join Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'ordering': ['-join_date'],
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Child's Name")),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10, null=True, verbose_name='Gender')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='membership.member', verbose_name='Parent Member')),
            ],
            options={
                'verbose_name': 'Child',
                'verbose_name_plural': 'Children',
                'ordering': ['date_of_birth'],
            },
        ),
        migrations.CreateModel(
            name='MembershipFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_type', models.CharField(choices=[('REGULAR', 'Regular'), ('LIFETIME', 'Lifetime Membership')], max_length=20, verbose_name='Membership Type')),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('ONLINE', 'Online Payment'), ('CHEQUE', 'Cheque')], max_length=20, verbose_name='Payment Mode')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fee Amount')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Membership Fee',
                'verbose_name_plural': 'Membership Fees',
                'ordering': ['membership_type', 'payment_mode'],
                'unique_together': {('membership_type', 'payment_mode')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount Paid')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name='Payment Date')),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('ONLINE', 'Online Payment'), ('CHEQUE', 'Cheque')], max_length=20, verbose_name='Payment Mode')),
                ('transaction_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Transaction Reference/Cheque Number')),
                ('receipt_number', models.CharField(max_length=50, unique=True, verbose_name='Receipt Number')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('collected_by', models.CharField(blank=True, max_length=200, null=True, verbose_name='Collected By')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='membership.member', verbose_name='Member')),
                ('membership_fee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='membership.membershipfee', verbose_name='Fee Structure')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
