# Generated by Django 6.0 on 2025-12-06 08:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('address', models.TextField(verbose_name='Address')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('photograph', models.ImageField(blank=True, help_text="Upload member's photograph (JPG, PNG)", null=True, upload_to='member_photos/', verbose_name='Photograph')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True, verbose_name='Gender')),
                ('father_name', models.CharField(max_length=200, verbose_name="Father's Name")),
                ('grandfather_name', models.CharField(blank=True, max_length=200, null=True, verbose_name="Grandfather's Name")),
                ('spouse_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Spouse Name')),
                ('citizenship_number', models.CharField(max_length=50, unique=True, verbose_name='Citizenship Number')),
                ('citizenship_issue_date', models.DateField(blank=True, null=True, verbose_name='Citizenship Issue Date')),
                ('citizenship_issue_district', models.CharField(blank=True, max_length=100, null=True, verbose_name='Citizenship Issue District')),
                ('membership_type', models.CharField(choices=[('REGULAR', 'Regular'), ('LIFETIME', 'Lifetime Membership')], default='REGULAR', max_length=20, verbose_name='Membership Type')),
                ('membership_number', models.CharField(max_length=50, unique=True, verbose_name='Membership Number')),
                ('join_date', models.DateField(default=django.utils.timezone.now, verbose_name='Join Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('payment_frequency', models.CharField(choices=[('ANNUAL', 'Annual'), ('MONTHLY', 'Monthly')], default='ANNUAL', help_text='How often member pays (only for Regular members)', max_length=20, verbose_name='Payment Frequency')),
                ('last_payment_date', models.DateField(blank=True, help_text='Date of most recent payment', null=True, verbose_name='Last Payment Date')),
                ('membership_valid_until', models.DateField(blank=True, help_text='Date when membership expires (null for lifetime members)', null=True, verbose_name='Membership Valid Until')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'ordering': ['-join_date'],
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Child's Name")),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True, verbose_name='Gender')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='membership.member', verbose_name='Parent Member')),
            ],
            options={
                'verbose_name': 'Child',
                'verbose_name_plural': 'Children',
                'ordering': ['date_of_birth'],
            },
        ),
        migrations.CreateModel(
            name='MembershipFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_type', models.CharField(choices=[('REGULAR', 'Regular'), ('LIFETIME', 'Lifetime Membership')], max_length=20, verbose_name='Membership Type')),
                ('payment_frequency', models.CharField(choices=[('ANNUAL', 'Annual'), ('MONTHLY', 'Monthly')], max_length=20, verbose_name='Payment Frequency')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fee Amount')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Membership Fee',
                'verbose_name_plural': 'Membership Fees',
                'ordering': ['membership_type', 'payment_frequency'],
                'unique_together': {('membership_type', 'payment_frequency')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Payment Amount')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name='Payment Date')),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('ONLINE', 'Online Payment'), ('CHEQUE', 'Cheque')], max_length=20, verbose_name='Payment Mode')),
                ('transaction_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Transaction Reference')),
                ('receipt_number', models.CharField(max_length=50, unique=True, verbose_name='Receipt Number')),
                ('collected_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Collected By')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='membership.member', verbose_name='Member')),
                ('membership_fee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='membership.membershipfee', verbose_name='Fee Structure')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_users', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
