# Generated by Django 5.0 on 2025-12-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='citizenship_number',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Citizenship Number'),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_type',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('LIFETIME', 'Lifetime Membership'), ('HONARARY', 'Honarary Membership')], default='REGULAR', max_length=20, verbose_name='Membership Type'),
        ),
        migrations.AlterField(
            model_name='member',
            name='payment_frequency',
            field=models.CharField(choices=[('ANNUAL', 'Annual'), ('MONTHLY', 'Monthly'), ('ONE-TIME', 'Once for a Lifetime'), ('HONARARY', 'Given on honour for a member')], default='ANNUAL', help_text='How often member pays (only for Regular members)', max_length=20, verbose_name='Payment Frequency'),
        ),
        migrations.AlterField(
            model_name='membershipfee',
            name='membership_type',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('LIFETIME', 'Lifetime Membership'), ('HONARARY', 'Honarary Membership')], max_length=20, verbose_name='Membership Type'),
        ),
        migrations.AlterField(
            model_name='membershipfee',
            name='payment_frequency',
            field=models.CharField(choices=[('ANNUAL', 'Annual'), ('MONTHLY', 'Monthly'), ('ONE-TIME', 'Once for a Lifetime'), ('HONARARY', 'Given on honour for a member')], max_length=20, verbose_name='Payment Frequency'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_mode',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('ONLINE', 'Online Payment'), ('CHEQUE', 'Cheque'), ('HONARARY', 'No Payment Required')], max_length=20, verbose_name='Payment Mode'),
        ),
    ]
