# Generated by Django 6.0 on 2025-12-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.RemoveField(
            model_name='child',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='child',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='child',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='membershipfee',
            name='payment_mode',
            field=models.CharField(choices=[('ANNUAL', 'Annual'), ('MONTHLY', 'Monthly')], max_length=20, verbose_name='Payment Frequency'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Payment Amount'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='collected_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Collected By'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Transaction Reference'),
        ),
    ]
