# Generated by Django 6.0 on 2025-12-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_alter_payment_options_remove_child_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='last_payment_date',
            field=models.DateField(blank=True, help_text='Date of most recent payment', null=True, verbose_name='Last Payment Date'),
        ),
        migrations.AddField(
            model_name='member',
            name='membership_valid_until',
            field=models.DateField(blank=True, help_text='Date when membership expires (null for lifetime members)', null=True, verbose_name='Membership Valid Until'),
        ),
        migrations.AddField(
            model_name='member',
            name='payment_frequency',
            field=models.CharField(choices=[('ANNUAL', 'Annual'), ('MONTHLY', 'Monthly')], default='ANNUAL', help_text='How often member pays (only for Regular members)', max_length=20, verbose_name='Payment Frequency'),
        ),
    ]
