# Generated by Django 6.0 on 2025-12-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_member_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='photograph',
            field=models.ImageField(blank=True, help_text="Upload member's photograph (JPG, PNG)", null=True, upload_to='member_photos/', verbose_name='Photograph'),
        ),
    ]
